### PR TITLE
Warning fixes for conversion warnings

### PR DESCRIPTION
**Pull request by joachim-faulhaber**

### CODE REVIEW

**Comment by eldiener** [comment]
There are errors in your PR. Please fix. You have both less and more parentheses than you should in certain cases.

**Comment by zerkms** [comment]
Maybe I'm missing something, but what is the point to declare a variable as `unsigned long week` and then cast it to integer in `return static_cast<int>(week)`?

Does not it always fit an `int` size at the very first place?

**Comment by eldiener** [comment]
You have a point that 'week' could have been an 'int'. If you feel strongly about it can you create a separate PR for it ?

**Comment by zerkms** [comment]
@eldiener I technically could, I'm dealing with C++ for few last weeks so I don't feel confident to propose such significant (?) changes.

**Pull request merged**
