### PR TITLE
4543: fix ptime 2038 issue

### PR DESCRIPTION
**Pull request by jeking3**

### CODE REVIEW

**Comment by jeking3** [comment]
Could someone please comment on why this has not been merged?  Are there any additional things that need to be done?  This issue has been open for almost 8 years, so I'm trying to understand why this isn't getting any movement here or in boost trac #4543.

**Comment by jdmairs** [comment]
The mod to var_type in time_resolution_traits.hpp has changed the behavior of boost::serialization.  My archives (built with boost 1.64) using boost::serialization (inherently using time_serialization.hpp) no longer load because the hours, minutes, etc fields are now 8 bytes instead of 4 bytes.

**Comment by jeking3** [comment]
Sounds like we're missing a unit test somewhere.  I'll add this as an issue.

**Comment by nohajc** [comment]
Hi, I'm afraid from_time_t is broken again in the release. By the very next commit:
https://github.com/boostorg/date_time/commit/b1dc2b306ea6abb645b0e334e3d5bb1b5ed80818#diff-3e708bf547192e1f6a2d31d6d278496f

**Comment by jeking3** [comment]
I opened https://github.com/boostorg/date_time/issues/87 to track this - I assume that accurately captures the issue?  I think all the casting in that commit needs to be inspected for correctness.

**Pull request merged**
