### PR TITLE
pull request to make date-time all inline

### PR DESCRIPTION
**Pull request by JeffGarland**
See issue #134.

### CODE REVIEW

**Comment by pdimov** [comment]
This change breaks all Jamfiles that refer to date_time, and will break all Linux packages that link to it. (And all CMake projects that use the `date_time` component.)

When I made System header-only, I left a stub library there to avoid this.

**Comment by JeffGarland** [comment]
Ok I'll do that - I'm sure users will have the same issue.  But also isn't it better to submit pull requests for libs to end the dependence?

**Comment by pdimov** [comment]
There are hundreds if not thousands of packages outside Boost that either do the equivalent of `-lboost_date_time` in their Makefile or `find_package(Boost COMPONENTS date_time)` in their CMakeLists.txt - we can't find and fix them all; this will create problems for downstream packagers such as Debian etc.

Inside of Boost, yes, we can do that. I think that most places that linked to `/boost//system` are gone by now.

There are three ways to refer to DateTime from a Jamfile - `/boost//date_time`, `/boost/date_time//boost_date_time`, and `...path-to-libs.../date_time/build//boost_date_time`. (Maybe more, I'm not sure.)

**Comment by JeffGarland** [comment]
Stub coming soon.  So does the stub live forever then?  I was wondering what the distros like redhat, etc would do with this...

**Comment by pdimov** [comment]
I don't think I can remove the System stub anytime soon. There's no mechanism to inform people that they need to fix their Makefiles. Distros just ship libboost_system.a/.so as they've always done.

**Comment by JeffGarland** [comment]
ok, thanks for the assist.  pr #137 will go to develop as soon as the CI finishes.

**Pull request merged**
