### PR TITLE
trac-10087: update the time zone database to IANA 2016c

### PR DESCRIPTION
**Pull request by jeking3**
https://svn.boost.org/trac10/ticket/10087

### CODE REVIEW

**Comment by eldiener** [comment]
What was the previous time zone database ? Can you give a link to this information ? Is it possible this change will break user's code ? I am all for this but I want to understand the ramifications.

**Comment by jeking3** [comment]
Sorry I keep forgetting to add the link to the trac issue...

https://svn.boost.org/trac10/ticket/10087

**Comment by jeking3** [comment]
@pdimov it looks like the automatic header code missed something in the failed build here.  Boost.Serialization is referring to Boost.Spirit which apparently wasn't pulled in by depinst.py:
https://travis-ci.org/boostorg/date_time/jobs/325820754

**Comment by pdimov** [comment]
https://travis-ci.org/boostorg/date_time/jobs/325820754#L528

**Comment by pdimov** [comment]
I probably need to check the return value :-)

**Comment by jeking3** [comment]
This change runs clean on all flavors of Windows and all linux I have tried.  The issue in the CI build is external to this PR.

**Pull request merged**
