### PR TITLE
make test clean up a file it creates

### PR DESCRIPTION
**Pull request by jeking3**

### CODE REVIEW

**Comment by eldiener** [comment]
Does date_time depend on filesystem other than your change in the test ? I am concerned that we are adding a dependency to filesystem which was not there before, even if that dependency be only in date_time tests. I am not saying that is necessarily wrong to do

**Comment by jeking3** [comment]
I'm not aware of any other dependency.  The other way to fix this is to add a .gitignore for the file the test creates but does not clean up, or find another way to get rid of it that is portable.  Thoughts?

**Comment by eldiener** [comment]
Is there any real testing problem with not deleting the file each time ? If there is not I would rather go the .gitignore route rather than add a testing dependency to filesystem.

**Comment by mclow** [comment]
Currently it just overwrites any previously existing file when you run the tests, right?
If that is the case, I'd be ok with the `.gitignore` route. Maybe delete it in the "clean" target.

**Comment by jeking3** [comment]
It shows up after building when you do a "git status" because the file isn't cleaned up.
A .gitignore would fix the issue, however the project didn't have a .gitignore to begin with and I was concerned folks would not want one added if there wasn't one.  I'll change this to just add that file to .gitignore.

**Comment by swatanabe** [comment]
AMDG

On 12/22/2017 02:11 PM, Marshall Clow wrote:
> Currently it just overwrites any previously existing file when you run the tests, right?

Is this safe for parallel builds?

> If that is the case, I'd be ok with the `.gitignore` route. Maybe delete it in the "clean" target.
> 

In Christ,
Steven Watanabe

**Pull request closed without merging**
