### PR TITLE
Add Appveyor CI support

### PR DESCRIPTION
**Pull request by jeking3**
Results (with all test enabled): https://ci.appveyor.com/project/jeking3/date-time/build/1.0.2-develop

Wow, Trac has 149 open issues for date_time...

### CODE REVIEW

**Comment by jeking3** [comment]
Will you set up an appveyor account for this repository?  The way appveyor handles it seems pretty strange, and I don't know if the account is tied to boostorg or to the individual who sets it up as a repository admin. 
 If you don't want to manage it, I can do it, but I would need to request maintainer status to do it, which I suppose I could do since format and uuid are in order. :)

**Comment by eldiener** [comment]
I was able to add date_time to Appveyor. It shows up under my Appveyor account.

**Comment by jeking3** [comment]
I don't see it kicking off a build: https://github.com/boostorg/date_time/pull/57

**Comment by eldiener** [comment]
It shows up under my appveyor account that it did and was successful.

**Comment by jeking3** [comment]
You want to enable the boostorg/date_time under your account, not eldiener/date_time.  I still don't see them running on pull requests, for example from yesterday: https://github.com/boostorg/date_time/pull/58

**Comment by eldiener** [comment]
All I know is that when I bring up Appveyor with my account login I see date_time because I added it. I am not sure what you mean by "your account" versus eldiener/date_time.

**Comment by jeking3** [comment]
It's the difference between adding your personal fork or the boostorg fork.

**Comment by eldiener** [comment]
I added the boost version of date_time to the Appveyor tests. All tests I have added to Appveyor under my login to Appveyor are of Boost libraries. Why am I supposed to fork a library and add it to Appveyor ? Am I sujpposed to login to Appveyor under some sort of Boost account ? If so how do I do that ?

**Comment by jeking3** [comment]
If you have admin access to the boostorg/date_time repository, it should show up in your appveyor account.. it'll look like this (sorry for the resolution, my laptop screen is 4KUHD):
image

**Comment by eldiener** [comment]
It shows up in my Appveyor account as another project which is run whenever date_time on Github gets updated. I do not see the Boostorg icon you are showing above. I just see a list of projects. All the projects listed are for the public Boostorg version of a library on Github and not for any of my own personal libraries on Github. Maybe I am supposed to sign on to Appveyor using some sort of Boostorg sign on but I do not know what that is.

**Comment by jeking3** [comment]
I think someone needs to add you as an admin on that repository in order to see it.

**Comment by eldiener** [comment]
I can see it fine when I am logged in to Appveyor. I do not understand what you are saying. You seem to think I have do something so that you know the result of the Appveyor run, but I do not know what I am supposed to do since I can see the result whenever I go to my Appveyor account online.

**Comment by jeking3** [comment]
Since you don't see date_time under "boostorg" then you are probably just getting branch update builds on your fork.

**Comment by eldiener** [comment]
I already told you that I do not have a fork of date_time.

**Pull request merged**
